Algoritmo "Desenvolvimento de Aplicação de Cálculo de Sequências Lógicas"
// API - 1° Semestre
//
// Professores:
//   Fabiano Sabha Walczak
//   Leonidas Lopes de Melo
//
// Descrição:
//   Interface de console calculadora de diversas sequências
//   lógicas matemáticas, com menu para seleção de 9 (nove)
//   opções diferentes.
//
// Equipe:
//   Weslley José Pereira de Moraes - Product Owner
//   João Victor Graciolli Ramos - Scrum Master
//   Ana - Developer
//   Eduardo Nakano - Developer
//   Leonardo Kenzo Okuno - Developer
//   Miguel Vitale - Developer
//   Olavo Salles - Developer
//
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo